### ISSUE TITLE
sequelize.sync() is called in every resolver

### ISSUE THREAD

**Issue by TimKolberger** [SaraVieira/graphql-workshop#6]
`sequelize.sync()` is called in every resolver but just needs to be called once after the model is defined.
Basically you are checking every time someone fires a query if the database is in sync with your defined model, but it won't change at runtime.

https://github.com/SaraVieira/graphql-workshop/blob/65e2f10edf19076b999f678113a4bca21e437651/4.1%20-%20server-combine-solution/resolvers.js#L29

**Comment by SaraVieira** [comment]
Very good point ! Changed :D
